---
title: "About"
---

We are SimBioSys (Simulating Biological Systems) group at Empa, St Gallen.

```{r out.width='100%', echo=FALSE,message=FALSE, warning=FALSE}
library(rgdal)
library(rgeos)
library(hrbrthemes)
library(ggplot2)
library(extrafont) 
library(dplyr)
library(viridisLite)

library(leaflet)
leaflet() %>% addTiles() %>%
  setView(9.3414, 47.41273, zoom = 17) %>%
  addPopups(
    9.3414,47.41273, 
    'We are here at <b>Empa</b>, St. Gallen'
  )
```




This website was created to enhance the visualization of the datasets discussed in the paper "Evaporative cooling devices for postharvest storage: where to best use then and how well do they work?". 

You can find the paper here:(hyperlink coming soon)


```{r out.width='100%', echo=FALSE,message=FALSE, warning=FALSE}
library(dplyr)
library(maps)
library(ggplot2)
library(ggthemes)

map_data("world") %>% 
  filter(region != "Antarctica") %>% 
  ggplot(aes(long, lat, group = paste(region, group))) + 
  geom_polygon() + 
  coord_fixed() +
  theme_map()
```

