---
title: "World map"
---


```{r, echo=FALSE, message=FALSE, results='hide',warning=FALSE}
library(rgdal)
library(rgeos)
library(hrbrthemes)
library(ggplot2)
library(extrafont) 
library(tidyverse)
library(raster)
library(dplyr)
library(viridisLite)
library(leaflet)



library(data.table)
library(sp)
library(tmap)    # for static and interactive maps
library(sf)
library(mapview)
library(leafsync)
library(viridis)


setwd("K:/Sims-shoji/2021_Charcoal/boundary/world")
world <- readOGR(dsn = "world_countries_2", layer = "ne_10m_admin_0_countries")
world_f<-fortify(world,region = "sovereignt" )

setwd("K:/Sims-shoji/2021_Charcoal")
world_2020<-read.csv("world_2020_empiricalTwb.csv")
world_2020$month = factor(world_2020$month, levels=month.abb)
# concert to data.frame to tbl_df
world_2020<-as_tibble(world_2020)
```
```{r, echo=FALSE, message=FALSE, results='hide',warning=FALSE}
addLegend_decreasing <- function (map, position = c("topright", "bottomright", "bottomleft","topleft"),
                                  pal, values, na.label = "NA", bins = 7, colors, 
                                  opacity = 0.5, labels = NULL, labFormat = labelFormat(), 
                                  title = NULL, className = "info legend", layerId = NULL, 
                                  group = NULL, data = getMapData(map), decreasing = FALSE) {
  
        position <- match.arg(position)
        type <- "unknown"
        na.color <- NULL
        extra <- NULL
        if (!missing(pal)) {
            if (!missing(colors)) 
                stop("You must provide either 'pal' or 'colors' (not both)")
            if (missing(title) && inherits(values, "formula")) 
                title <- deparse(values[[2]])
            values <- evalFormula(values, data)
            type <- attr(pal, "colorType", exact = TRUE)
            args <- attr(pal, "colorArgs", exact = TRUE)
            na.color <- args$na.color
            if (!is.null(na.color) && col2rgb(na.color, alpha = TRUE)[[4]] == 
                    0) {
                na.color <- NULL
            }
            if (type != "numeric" && !missing(bins)) 
                warning("'bins' is ignored because the palette type is not numeric")
            if (type == "numeric") {
                cuts <- if (length(bins) == 1) 
                    pretty(values, bins)
                else bins   
                if (length(bins) > 2) 
                    if (!all(abs(diff(bins, differences = 2)) <= 
                                     sqrt(.Machine$double.eps))) 
                        stop("The vector of breaks 'bins' must be equally spaced")
                n <- length(cuts)
                r <- range(values, na.rm = TRUE)
                cuts <- cuts[cuts >= r[1] & cuts <= r[2]]
                n <- length(cuts)
                p <- (cuts - r[1])/(r[2] - r[1])
                extra <- list(p_1 = p[1], p_n = p[n])
                p <- c("", paste0(100 * p, "%"), "")
                if (decreasing == TRUE){
                    colors <- pal(rev(c(r[1], cuts, r[2])))
                    labels <- rev(labFormat(type = "numeric", cuts))
                }else{
                    colors <- pal(c(r[1], cuts, r[2]))
                    labels <- rev(labFormat(type = "numeric", cuts))
                }
                colors <- paste(colors, p, sep = " ", collapse = ", ")
            }
            else if (type == "bin") {
                cuts <- args$bins
                n <- length(cuts)
                mids <- (cuts[-1] + cuts[-n])/2
                if (decreasing == TRUE){
                    colors <- pal(rev(mids))
                    labels <- rev(labFormat(type = "bin", cuts))
                }else{
                    colors <- pal(mids)
                    labels <- labFormat(type = "bin", cuts)
                }
            }
            else if (type == "quantile") {
                p <- args$probs
                n <- length(p)
                cuts <- quantile(values, probs = p, na.rm = TRUE)
                mids <- quantile(values, probs = (p[-1] + p[-n])/2, na.rm = TRUE)
                if (decreasing == TRUE){
                    colors <- pal(rev(mids))
                    labels <- rev(labFormat(type = "quantile", cuts, p))
                }else{
                    colors <- pal(mids)
                    labels <- labFormat(type = "quantile", cuts, p)
                }
            }
            else if (type == "factor") {
                v <- sort(unique(na.omit(values)))
                colors <- pal(v)
                labels <- labFormat(type = "factor", v)
                if (decreasing == TRUE){
                    colors <- pal(rev(v))
                    labels <- rev(labFormat(type = "factor", v))
                }else{
                    colors <- pal(v)
                    labels <- labFormat(type = "factor", v)
                }
            }
            else stop("Palette function not supported")
            if (!any(is.na(values))) 
                na.color <- NULL
        }
        else {
            if (length(colors) != length(labels)) 
                stop("'colors' and 'labels' must be of the same length")
        }
        legend <- list(colors = I(unname(colors)), labels = I(unname(labels)), 
                                     na_color = na.color, na_label = na.label, opacity = opacity, 
                                     position = position, type = type, title = title, extra = extra, 
                                     layerId = layerId, className = className, group = group)
        invokeMethod(map, data, "addLegend", legend)
        }
```


NOTE: Changing the base map layers hide the temperature depression map. You can unclick and click the temperature depression map to reappear on top of the base map.Sorry for inconvenience.
```{r out.width='100%', echo=FALSE, warning=FALSE,message=FALSE}

world_2020<-as_tibble(world_2020)
coolT_world_2020_05<-world_2020%>% filter(month =="May") %>% dplyr::select(x,y,cool_t_round)

df_coolT_world_2020_05 <- rasterFromXYZ(coolT_world_2020_05)  #Convert first two columns as lon-lat and third as value           

crs(df_coolT_world_2020_05) <- sp::CRS("+init=EPSG:4326")
pal <- colorNumeric("viridis", values(df_coolT_world_2020_05),na.color = NA)

labels <- sprintf("%s",
                  world$sovereignt
) %>% lapply(htmltools::HTML)

leaflet() %>% 
  # Base groups
  addTiles(group = "OSM (default)") %>%
  # check out : http://leaflet-extras.github.io/leaflet-providers/preview/
    addProviderTiles(providers$Stamen.Terrain, group = "Terrain",providerTileOptions(zIndex= -10000)) %>%
      addProviderTiles(providers$OpenTopoMap, group = "Topo",providerTileOptions(zIndex= -10)) %>%
  addProviderTiles(providers$NASAGIBS.ViirsEarthAtNight2012, group = "Night (NASA)",providerTileOptions(zIndex= -10)) %>%
  addProviderTiles(providers$ Esri.WorldImagery, group = "Imagery (Esri)",providerTileOptions(zIndex= -10)) %>%
    clearImages() %>%
  setView(lat= 47.41273, lng= 9.3414, zoom=2) %>%
  
   # Overlay groups
  addScaleBar()%>%
  addLegend_decreasing(pal = pal, values = values( df_coolT_world_2020_05 ),  position = "bottomright", decreasing = TRUE, title = "Temperature</br>depression</br>(°C)</br>May 2020")%>%
  addMiniMap(position = "bottomleft")  %>%
  
    addPolygons(data = world, 
                fillOpacity = 0,
                weight = 1,
                color = "white",
                group = "Border",
                # highlightOptions = highlightOptions(
                #   weight = 5,
                #   color = "#666",
                #   dashArray = "",
                #   fillOpacity = 0,
                #   bringToFront = TRUE)
                label = labels,
                labelOptions = labelOptions(
                 style = list("font-weight" = "normal", padding = "3px 8px"),
                 textsize = "15px",direction = "auto")
                )%>%
    addRasterImage( df_coolT_world_2020_05 , colors = pal, opacity = 0.8, group = "Temp dep")%>%
  
  # Layers control
   addLayersControl(
    baseGroups = c("OSM (default)","Terrain","Topo", "Night (NASA)", "Imagery (Esri)"),
    overlayGroups = "Temp dep",
    options = layersControlOptions(collapsed = FALSE, autoZIndex = FALSE))

```

```{r out.width='100%', echo=FALSE,warning=FALSE,message=FALSE}
# https://cran.r-project.org/web/packages/leafsync/readme/README.html

coolT_wld_2020_01<-world_2020%>% filter(month =="Jan") %>% dplyr::select(x,y,cool_t_round)
df_coolT_wld_2020_01 <- rasterFromXYZ(coolT_wld_2020_01)  #Convert first two columns as lon-lat and third as value
crs(df_coolT_wld_2020_01) <- sp::CRS("+init=EPSG:4326")

coolT_wld_2020_04<-world_2020%>% filter(month =="Apr") %>% dplyr::select(x,y,cool_t_round)
df_coolT_wld_2020_04 <- rasterFromXYZ(coolT_wld_2020_04)  #Convert first two columns as lon-lat and third as value
crs(df_coolT_wld_2020_04) <- sp::CRS("+init=EPSG:4326")

coolT_wld_2020_07<-world_2020%>% filter(month =="Jul") %>% dplyr::select(x,y,cool_t_round)
df_coolT_wld_2020_07 <- rasterFromXYZ(coolT_wld_2020_07)  #Convert first two columns as lon-lat and third as value
crs(df_coolT_wld_2020_07) <- sp::CRS("+init=EPSG:4326")

coolT_wld_2020_10<-world_2020%>% filter(month =="Oct") %>% dplyr::select(x,y,cool_t_round)
df_coolT_wld_2020_10 <- rasterFromXYZ(coolT_wld_2020_10)  #Convert first two columns as lon-lat and third as value
crs(df_coolT_wld_2020_10) <- sp::CRS("+init=EPSG:4326")
```


```{r out.width='100%', echo=FALSE,warning=FALSE,message=FALSE}
## view different aspects of same data set
# install.packages("spatialEco")
library(spatialEco)
w1 <- mapview(df_coolT_wld_2020_01, na.color= NA,alpha.regions=0.5,col.regions = viridis(8), at = c(0, 2.5, 5, 7.5, 10, 15, 22), layer.name = "January 2020")

w2 <- mapview(df_coolT_wld_2020_04, na.color= NA,alpha.regions=0.5,col.regions = viridis(8), at = c(0, 2.5, 5, 7.5, 10, 15, 22),layer.name = "April 2020")

w3 <- mapview(df_coolT_wld_2020_07, na.color= NA,alpha.regions=0.5,col.regions = viridis(8), at = c(0, 2.5, 5, 7.5, 10, 15, 22),layer.name = "July 2020")

w4 <- mapview(df_coolT_wld_2020_10, na.color= NA,alpha.regions=0.5,col.regions = viridis(8), at = c(0, 2.5, 5, 7.5, 10, 15, 22),layer.name = "October 2020")

sync(w1, w2, w3, w4) # 4 panels synchronised

```
# World map
```{r out.width='100%', echo=FALSE, warning=FALSE}
library(leaflet)

m <- leaflet()
m <- addTiles(m)
m
```
